name: Docker Image CI

on:
  push:
    branches: [ "branch_29092025" ]
  pull_request:
    branches: [ "branch_29092025" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Debug username
        run: echo "DockerHub username is ${{ secrets.DOCKERHUB_USERNAME }}"
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-docker-api:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-docker-api:latest
